[package]
name = "charter"
version = "0.1.0"
edition = "2021"

[dependencies]
clippy = "0.0.302"
crossterm = "0.28.1"
fmt = "0.1.0"
plotters = "0.3.7"
ratatui = { version = "0.29.0", features = ["all-widgets", "unstable-widget-ref"]}
